<!--Do NOT change this file manually, it is being generated by 'fws icons' command.-->

<template>
    <component v-bind:is="component"/>
</template>

<script>
    import startcase from 'lodash.startcase';
    import ArrowDown from '../../../../assets/svg/ico-arrow-down.svg';
    import ArrowLeft from '../../../../assets/svg/ico-arrow-left.svg';
    import ArrowRight from '../../../../assets/svg/ico-arrow-right.svg';
    import ArrowUp from '../../../../assets/svg/ico-arrow-up.svg';
    import BoneBreakFull from '../../../../assets/svg/ico-bone-break-full.svg';
    import BoneBreak from '../../../../assets/svg/ico-bone-break.svg';
    import BoneFull from '../../../../assets/svg/ico-bone-full.svg';
    import Bone from '../../../../assets/svg/ico-bone.svg';
    import Bookmark from '../../../../assets/svg/ico-bookmark.svg';
    import ChevronRight from '../../../../assets/svg/ico-chevron-right.svg';
    import Cup from '../../../../assets/svg/ico-cup.svg';
    import Dog from '../../../../assets/svg/ico-dog.svg';
    import Email from '../../../../assets/svg/ico-email.svg';
    import Facebook from '../../../../assets/svg/ico-facebook.svg';
    import Happy from '../../../../assets/svg/ico-happy.svg';
    import House from '../../../../assets/svg/ico-house.svg';
    import Instagram from '../../../../assets/svg/ico-instagram.svg';
    import Letter from '../../../../assets/svg/ico-letter.svg';
    import Location from '../../../../assets/svg/ico-location.svg';
    import Lock from '../../../../assets/svg/ico-lock.svg';
    import Paw from '../../../../assets/svg/ico-paw.svg';
    import Phone from '../../../../assets/svg/ico-phone.svg';
    import PlusCircle from '../../../../assets/svg/ico-plus-circle.svg';
    import Quote from '../../../../assets/svg/ico-quote.svg';
    import Twitter from '../../../../assets/svg/ico-twitter.svg';
    import User from '../../../../assets/svg/ico-user.svg';
    import Whatsapp from '../../../../assets/svg/ico-whatsapp.svg';
    import XmarkSolid from '../../../../assets/svg/ico-xmark-solid.svg';

    export default {
        props: {
            iconName: {
                type: String,
                required: true
            }
        },
        components: {
            ArrowDown,
            ArrowLeft,
            ArrowRight,
            ArrowUp,
            BoneBreakFull,
            BoneBreak,
            BoneFull,
            Bone,
            Bookmark,
            ChevronRight,
            Cup,
            Dog,
            Email,
            Facebook,
            Happy,
            House,
            Instagram,
            Letter,
            Location,
            Lock,
            Paw,
            Phone,
            PlusCircle,
            Quote,
            Twitter,
            User,
            Whatsapp,
            XmarkSolid,

        },
        computed: {
            component() {
                return startcase(this.iconName.replace('ico-', '')).replace(' ', '');
            }
        }
    };
</script>
